# Generated by Django 6.0.1 on 2026-02-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_mfa_recovery_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the user requested account deletion', null=True),
        ),
    ]
