# Generated by Django 6.0.1 on 2026-02-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_deletion_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_policy_version',
            field=models.IntegerField(default=0, help_text='Version of the Terms of Service accepted by the user'),
        ),
        migrations.AddField(
            model_name='user',
            name='policy_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the user accepted the latest policy', null=True),
        ),
    ]
